### ISSUE TITLE
[FEATURE] Allow multiple additional cidr to vpc and NATGW fixes

### ISSUE THREAD

**Issue by rverma-nsl** [aws-samples/aws-secure-environment-accelerator#665]
**Required Basic Info**
1. Allow to attach multiple vpc cidr (currently only 1 additional i.e using cidr2 is supported)
2. Allow ipv6 and egress only gateway (dualstack)
- Accelerator Version:  1.30.0

**Is your feature request related to a problem? Please describe.**
We usually have requirements for extra large vpcs and in those scenarios having 4 or 5 additional cidr attached is quiet essential.
In addition to that we prefer to use egress only gateway in addition to nat gateways when we need to secure our workload but no need of static ip. This saves on both data transfer cost as well as nat per hour cost :)

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
Managing the whole vpc module out of ASEA

**Comment by Brian969** [comment]
Notes:
- Item 1 is likely an easy tweak, could involve simply changing cidr2 to an array
- Item 2 will be quite a bit of work (last I checked most ipv6 'stuff' was not supported by CFN and would require converting all networking to custom resources)

**Comment by rverma-nsl** [comment]
First I have implemented, sending PR. For 2nd I found this https://gist.github.com/milesjordan/d86942718f8d4dc20f9f331913e7367a. I believe ipv6 is now fully supported

**Comment by Brian969** [comment]
- You are correct for VPC's: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpccidrblock.html, which is great!
- FYI: appears it is still not supported for TGW attachments :-(, any other spots we need to consider?

**Comment by rverma-nsl** [comment]
Just in case if I am getting this right, seems like tgw already support ipv6. https://docs.aws.amazon.com/vpc/latest/tgw/tgw-transit-gateways.html
By the way our usecase is to implement egress only gateways which provide the benefits of nat security without the cost implications :)

**Comment by Brian969** [comment]
sorry, should have been clearer - TGW supports IPv6, CFN for TGW does not, yet.

**Comment by Brian969** [comment]
Planned for v1.3.3

**Comment by Brian969** [comment]
@rverma-nsl - we fixed the NATGW issues (now updated properly using config file) and accepted your multi-CIDR enhancements for CIDR2 - both merged into main branch, for release with v1.3.3.  We appreciate the contribution!
